MidtermExam/FrontEnd/Models/ErrorViewModel.cs
namespace FrontEnd.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MidtermExam/FrontEnd/Models/PersonaViewModel.cs
namespace FrontEnd.Models;

public class PersonaViewModel
{
    public int PersonaId { get; set; }
    public string Cedula { get; set; }
    public string Nombre { get; set; }
}

MidtermExam/FrontEnd/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FrontEnd.Models;

namespace FrontEnd.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MidtermExam/FrontEnd/Controllers/PersonaController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using FrontEnd.Services;

namespace FrontEnd.Controllers;

public class PersonaController : Controller
{
    private readonly ILogger<PersonaController> _logger;
    private readonly PersonaService _PersonaService;

    public PersonaController(PersonaService PersonaService, ILogger<PersonaController> logger)
    {
        _PersonaService = PersonaService;
        _logger = logger;
    }

    [HttpGet]
    public ActionResult Index()
    {
        _logger.LogInformation("Retrieving all categories.");
        return View(_PersonaService.GetAll());
    }

    [HttpGet]
    public ActionResult Details(int id)
    {
        _logger.LogInformation($"Retrieving details for Persona with ID: {id}.");
        return View(_PersonaService.Get(id));
    }

    [HttpGet]
    public ActionResult Create()
    {
        _logger.LogInformation("Rendering Persona create form.");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(PersonaViewModel Persona)
    {
        try
        {
            _logger.LogInformation("Attempting to create a new Persona.");
            PersonaViewModel createdPersona = _PersonaService.Create(Persona);
            _logger.LogInformation($"Created Persona with ID: {createdPersona.PersonaId}");
            return RedirectToAction("Details", new { id = createdPersona.PersonaId });
        }
        catch
        {
            _logger.LogError("An error occurred while creating a new Persona.");
            return View();
        }
    }

    [HttpGet]
    public ActionResult Edit(int id)
    {
        _logger.LogInformation($"Rendering Persona edit form for Persona with ID: {id}.");
        return View(_PersonaService.Get(id));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(PersonaViewModel Persona)
    {
        try
        {
            _logger.LogInformation($"Attempting to update Persona with ID: {Persona.PersonaId}.");
            _PersonaService.Edit(Persona);
            _logger.LogInformation($"Updated Persona with ID: {Persona.PersonaId}.");
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            _logger.LogError($"An error occurred while updating Persona with ID: {Persona.PersonaId}.");
            return View();
        }
    }

    [HttpGet]
    public ActionResult Delete(int id)
    {
        _logger.LogInformation($"Rendering Persona delete form for Persona with ID: {id}.");
        return View(_PersonaService.Get(id));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(PersonaViewModel Persona)
    {
        try
        {
            _logger.LogInformation($"Attempting to delete Persona with ID: {Persona.PersonaId}.");
            _PersonaService.Delete(Persona.PersonaId);
            _logger.LogInformation($"Deleted Persona with ID: {Persona.PersonaId}.");
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            _logger.LogError($"An error occurred while deleting Persona with ID: {Persona.PersonaId}.");
            return View();
        }
    }
}

MidtermExam/FrontEnd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MidtermExam/FrontEnd/Views/Persona/Create.cshtml
@model FrontEnd.Models.PersonaViewModel

@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PersonaViewModel</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Cedula" class="control-label"></label>
				<input asp-for="Cedula" class="form-control" />
				<span asp-validation-for="Cedula" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Nombre" class="control-label"></label>
				<input asp-for="Nombre" class="form-control" />
				<span asp-validation-for="Nombre" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

MidtermExam/FrontEnd/Views/Persona/Delete.cshtml
@model FrontEnd.Models.PersonaViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonaViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
	    @Html.HiddenFor(model => model.PersonaId)
	    <input type="submit" value="Delete" class="btn btn-danger"/> |
	    <a asp-action="Index">Back to List</a>
    </form>
</div>

MidtermExam/FrontEnd/Views/Persona/Details.cshtml
@model FrontEnd.Models.PersonaViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PersonaViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {id = Model.PersonaId}) |
    <a asp-action="Index">Back to List</a>
</div>

MidtermExam/FrontEnd/Views/Persona/Edit.cshtml
@model FrontEnd.Models.PersonaViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PersonaViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonaId" class="control-label"></label>
                <input asp-for="PersonaId" class="form-control" />
                <span asp-validation-for="PersonaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MidtermExam/FrontEnd/Views/Persona/Index.cshtml
@model IEnumerable<FrontEnd.Models.PersonaViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id=item.PersonaId}) |
                    @Html.ActionLink("Details", "Details", new {id=item.PersonaId}) |
                    @Html.ActionLink("Delete", "Delete", new {id=item.PersonaId})
            </td>
        </tr>
}
    </tbody>
</table>

MidtermExam/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Midterm Exam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	                    </li>
	                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Index">Persona</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>